# Generated by Django 5.0.1 on 2024-02-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', models.CharField(max_length=11)),
                ('item', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=1)),
                ('contact', models.CharField(max_length=11)),
                ('circle_radio', models.CharField(max_length=11)),
                ('lost_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
