# Generated by Django 5.0.1 on 2024-02-05 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_latitude', models.IntegerField()),
                ('lost_longetude', models.IntegerField()),
                ('item', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('circle_radio', models.IntegerField()),
                ('lost_date', models.DateTimeField(auto_now=True)),
                ('lost_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LostUser',
        ),
    ]
