# Generated by Django 5.0.1 on 2024-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lostitem_delete_lostuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='circle_radio',
            field=models.IntegerField(null=True),
        ),
    ]
