# Generated by Django 5.0.1 on 2024-02-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_lostitem_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='item_status',
        ),
    ]
