# Generated by Django 5.0.1 on 2024-02-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_lostitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='item_status',
            field=models.BooleanField(default=False),
        ),
    ]
