# Generated by Django 5.0.1 on 2024-02-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_lostitem_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitem',
            old_name='lost_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='lost_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='lost_longetude',
            new_name='longetude',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='lost_fk',
            new_name='user_lost',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='loc',
            field=models.CharField(default=None, max_length=65),
            preserve_default=False,
        ),
    ]
